# Generated by Django 4.2.5 on 2023-09-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
